<?php declare(strict_types=1);

namespace Inferred\TypeCasters;

/**
 * Implements downcast for php. Allows IDE to infer methods and fields inferred from the variable.
 * Since PHP doesn't have type casts this class doesn't do any actual work.
 *
 * @autogenerated 2021-12-30 19:05:23
 */
class SimpleTagTypeCaster
{
	/**
	 * @var \Inferred\PhpDoc\SimpleTag|mixed Value that's going to be cast
	 */
	protected mixed $value;


	/**
	 * @param \Inferred\PhpDoc\SimpleTag|mixed $value Value that needs to be cast
	 */
	public function __construct(mixed $value = null)
	{
		$this->value = $value;
	}


	/**
	 * Checks if the object is of desired type
	 *
	 * @return bool
	 */
	public function hasValue(): bool
	{
		return $this->value instanceof \Inferred\PhpDoc\SimpleTag;
	}


	/**
	 * Returns the object of the correct type
	 *
	 * @return \Inferred\PhpDoc\SimpleTag|null
	 */
	public function getValue(): ?\Inferred\PhpDoc\SimpleTag
	{
		if (!$this->hasValue()) {
		    return null;
		}
		return $this->value;
	}
}
